name: libraryfront
description: Project for fullstack.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Ui
  extended_masked_text: ^2.3.1
  pinput: ^2.2.31
  timer_count_down: ^2.2.2
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_rating_bar: ^4.0.1
  chips_choice: ^3.0.0
  cached_network_image: ^3.2.3
  chewie: ^1.5.0
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.1
  cupertino_icons: ^1.0.2
  rating_summary: ^1.0.2+1
  dropdown_button2: ^2.1.3
  syncfusion_flutter_datepicker: ^21.2.3
  flutter_html: ^3.0.0-beta.2
  onboarding: ^3.1.0
  flutter_layout_grid: ^2.0.3
  dots_indicator: ^2.0.0
  flutter_switch: ^0.3.2
  cool_alert: ^1.1.0
  pull_to_refresh_flutter3: ^2.0.1

  #asset management
  flutter_svg: ^2.0.5
  spider: ^4.2.0

  # Internet connectivity
  connectivity_plus: ^4.0.0

  #state management
  bloc: ^8.1.2
  meta: ^1.8.0
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  bloc_concurrency: ^0.2.2

  l: ^3.2.0

  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

  #network
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_db_store: ^5.1.0

  #router
  auto_route: ^5.0.4

  # Dependency injection
  injectable: ^2.1.2
  get_it: ^7.2.0

    # Local Storage
  quiver: ^3.2.1
  shared_preferences: ^2.1.2
  path_provider: ^2.0.8
  path: ^1.8.2
  sqlite3_flutter_libs: ^0.5.0
  drift: ^2.8.0
  flutter_secure_storage: ^8.0.0

  # Features
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.0.1
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.2
  drift_dev: ^2.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
